### ISSUE TITLE
Delete all rows from table

### ISSUE THREAD

**Issue by chinchy** [ods/aiochsa#20]
I wanna delete all rows from my table, but I'd have exception `sqlalchemy.exc.CompileError: WHERE clause is required`

My code:
`await test_db.execute(electricity_battery.delete())`

**Comment by ods** [comment]
The `WHERE` clause [is mandatory](https://clickhouse.com/docs/en/sql-reference/statements/alter/delete/) in `ALTER TABLE … DELETE` mutation. You can overcome this by using `electricity_battery.delete().where(sqlalchemy.true())`. If you think this is what driver have to do by default, please suggest this change [in clickhouse-sqlalchemy](https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/6ea0501d176870175e36c51d9fde11481b055266/clickhouse_sqlalchemy/drivers/base.py#L379-L388).
